# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harvey < Formula
  desc "Remove Extra Stuff from Markdown"
  homepage "https://github.com/mikfreedman/harvey"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.0/harvey_v0.1.0_Darwin_x86_64.tar.gz"
      sha256 "395bef877fced894e01ac235dcfd4559ce0d35af552cd6bfe28b1102ed16d25e"

      def install
        bin.install "harvey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.0/harvey_v0.1.0_Darwin_arm64.tar.gz"
      sha256 "64b03007289e5a00f5959f3dea8dfcc5d3541a24f7dfb419dfe9927a26768e01"

      def install
        bin.install "harvey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.0/harvey_v0.1.0_Linux_arm64.tar.gz"
      sha256 "4bee69f1bb1f564116be94f32a9e1a2defd70e12241ac2f24b12d91e6cbc092f"

      def install
        bin.install "harvey"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.0/harvey_v0.1.0_Linux_x86_64.tar.gz"
      sha256 "21383edcf4cd8be914cc6702aedacf5a4b97d85774e8a6dbe5f321f07528c3a6"

      def install
        bin.install "harvey"
      end
    end
  end

  test do
    system "#{bin}/harvey --version"
  end
end
