# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harvey < Formula
  desc "Remove Extra Stuff from Markdown"
  homepage "https://github.com/mikfreedman/harvey"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.2/harvey_v0.1.2_Darwin_x86_64.tar.gz"
      sha256 "52c735640ff6318d046f1737b92a4cc3d474cfc278f84680e7ad6a5f7c028945"

      def install
        bin.install "harvey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.2/harvey_v0.1.2_Darwin_arm64.tar.gz"
      sha256 "9afc23d51ca23b8e1e89142fb375c5c4ed623ee2b710eac9e453b1f0c7233ce4"

      def install
        bin.install "harvey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.2/harvey_v0.1.2_Linux_arm64.tar.gz"
      sha256 "12468801a15f023ce45de5b484f7ff0136ce3975ff61d97b304e622fc436b18e"

      def install
        bin.install "harvey"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.2/harvey_v0.1.2_Linux_x86_64.tar.gz"
      sha256 "e711ab4d78b0fcedd161c59c526a65e53aa101aa6861f6390365a88b752ccb99"

      def install
        bin.install "harvey"
      end
    end
  end

  test do
    system "#{bin}/harvey --version"
  end
end
