# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harvey < Formula
  desc "Remove Extra Stuff from Markdown"
  homepage "https://github.com/mikfreedman/harvey"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.1/harvey_v0.1.1_Darwin_x86_64.tar.gz"
      sha256 "007d070b70348262f5ddc0ee1c6dd50e7f2ce72496855f500925b344a8ca56c6"

      def install
        bin.install "harvey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.1/harvey_v0.1.1_Darwin_arm64.tar.gz"
      sha256 "aa66be69f980a92cfc68c3d504f66899b5fa4a2d345e42154422b97b463a03e7"

      def install
        bin.install "harvey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.1/harvey_v0.1.1_Linux_x86_64.tar.gz"
      sha256 "d939f764041c7acaec6fbbb6dcea6feeb00009f87b712d309a3ca412f982a3ff"

      def install
        bin.install "harvey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikfreedman/harvey/releases/download/v0.1.1/harvey_v0.1.1_Linux_arm64.tar.gz"
      sha256 "288f9aaff0145af05942d9698681c54483395a17b348be3aa16b2716b1048a41"

      def install
        bin.install "harvey"
      end
    end
  end

  test do
    system "#{bin}/harvey --version"
  end
end
